from __future__ import annotations

from pathlib import Path
from typing import Any

from app.config import get_settings
from app.tools.base import ModelExporter
from app.tools.glb_utils import write_placeholder_glb

_SUPPORTED_FORMATS = {"glb", "obj", "fbx"}


class MockModelExporter(ModelExporter):
    """Mock exporter for Phase 10. Writes a placeholder asset for the
    requested format so the export contract (a file exists at file_path)
    holds end-to-end. A real encoder pipeline can later replace this
    behind the same ModelExporter interface."""

    def export(self, model_id: str, file_path: str, format: str) -> dict[str, Any]:
        fmt = format.lower()
        if fmt not in _SUPPORTED_FORMATS:
            raise ValueError(f"unsupported export format: {format!r} (supported: {sorted(_SUPPORTED_FORMATS)})")

        settings = get_settings()
        relative_path = Path(settings.outputs_dir) / model_id / f"model.{fmt}"
        absolute_path = settings.resolve(str(relative_path))

        if fmt == "glb":
            write_placeholder_glb(absolute_path)
        else:
            # Real OBJ/FBX encoders come later (Phase 21); write a labeled
            # placeholder so the file-exists contract holds regardless.
            absolute_path.parent.mkdir(parents=True, exist_ok=True)
            absolute_path.write_text(
                f"# placeholder {fmt.upper()} export for {model_id}\n"
                "# generated by MockModelExporter -- not real geometry\n"
            )

        return {
            "success": True,
            "model_id": model_id,
            "format": fmt,
            "file_path": relative_path.as_posix(),
        }


def get_exporter() -> ModelExporter:
    return MockModelExporter()
