/**
 * Standardized Benchmark Test Cases (Phase 77).
 *
 * Covers standard, minimalist, complex, tolerance-stressed, multi-angle,
 * high-piece-count, and nesting-stressed scenarios.
 */

import type { BenchmarkTestCase } from "./types";

export const BENCHMARK_TEST_SUITE: BenchmarkTestCase[] = [
  {
    id: "bench_case_01",
    name: "Standard Desk Organizer",
    category: "standard_desk",
    prompt: "Design a 4-piece interlocking cardboard desk storage puzzle with standard 90-degree tab-slot joints",
    userPreferences: {
      targetPieceCount: 4,
      targetDimensions: { widthMm: 180, heightMm: 120, depthMm: 80 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "medium",
    },
    stressFactor: "none",
    tags: ["standard", "desk_storage", "tab_slot", "90deg"],
  },
  {
    id: "bench_case_02",
    name: "Minimalist Phone Stand",
    category: "minimalist_stand",
    prompt: "Design a sturdy 3-piece minimalist phone stand with quick insertion tabs",
    userPreferences: {
      targetPieceCount: 3,
      targetDimensions: { widthMm: 120, heightMm: 100, depthMm: 70 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "easy",
    },
    stressFactor: "none",
    tags: ["minimalist", "3_piece", "stand", "easy"],
  },
  {
    id: "bench_case_03",
    name: "Complex 6-Piece Interlocking Cube",
    category: "complex_interlock",
    prompt: "Design a 6-piece interlocking cube box puzzle with multiple constrained mating interfaces",
    userPreferences: {
      targetPieceCount: 6,
      targetDimensions: { widthMm: 140, heightMm: 140, depthMm: 140 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "hard",
    },
    stressFactor: "high_density_stress",
    tags: ["complex", "6_piece", "cube", "hard"],
  },
  {
    id: "bench_case_04",
    name: "Tight-Tolerance Joint Challenge",
    category: "tight_tolerance",
    prompt: "Design a precision interlocking connector with tight friction-fit tabs without laser kerf jamming",
    userPreferences: {
      targetPieceCount: 4,
      targetDimensions: { widthMm: 160, heightMm: 120, depthMm: 80 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "medium",
    },
    stressFactor: "clearance_stress",
    tags: ["tolerance_stress", "friction_fit", "clearance"],
  },
  {
    id: "bench_case_05",
    name: "Multi-Angle 45° Transition Puzzle",
    category: "multi_angle",
    prompt: "Design a triangular prism assembly with non-orthogonal 45-degree joining interfaces",
    userPreferences: {
      targetPieceCount: 4,
      targetDimensions: { widthMm: 150, heightMm: 130, depthMm: 90 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 45.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "medium",
    },
    stressFactor: "angle_stress",
    tags: ["multi_angle", "45deg", "non_orthogonal", "kinematics"],
  },
  {
    id: "bench_case_06",
    name: "Sheet Utilization Stress Challenge",
    category: "sheet_utilization_stress",
    prompt: "Design a compact 4-piece desk caddy optimized for cardboard sheet nesting with minimal scrap waste",
    userPreferences: {
      targetPieceCount: 4,
      targetDimensions: { widthMm: 200, heightMm: 140, depthMm: 90 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "medium",
    },
    stressFactor: "none",
    tags: ["sheet_nesting", "material_efficiency", "waste_reduction"],
  },
  {
    id: "bench_case_07",
    name: "High-Piece Count Modular Puzzle",
    category: "high_piece_count",
    prompt: "Design an 8-piece modular interlocking desktop organizer with tiered compartments",
    userPreferences: {
      targetPieceCount: 8,
      targetDimensions: { widthMm: 240, heightMm: 160, depthMm: 100 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "expert",
    },
    stressFactor: "high_density_stress",
    tags: ["8_piece", "modular", "high_density", "expert"],
  },
  {
    id: "bench_case_08",
    name: "Bilateral Symmetrical Modular Assembly",
    category: "symmetrical_modular",
    prompt: "Design a symmetrical 4-piece card stand with mirrored bilateral slot geometry",
    userPreferences: {
      targetPieceCount: 4,
      targetDimensions: { widthMm: 180, heightMm: 120, depthMm: 80 },
      preferredMaterialId: "cardboard-corrugated-2mm",
      defaultJoiningAngleDeg: 90.0,
      preferredJointType: "tab_slot",
      targetDifficulty: "medium",
    },
    stressFactor: "none",
    tags: ["symmetrical", "mirrored", "bilateral", "aesthetics"],
  },
];
