/**
 * Geometry tools — the "Shapes" category.
 *
 * Every tool here draws a new Part on the 2D canvas. They are pure metadata:
 * `kind: "draw"` tells Canvas2D to create a Part via `createPart` + `setPartShape`
 * on drag, using `createsShape` as the base outline. No `execute` is needed for
 * draw tools; the canvas owns the drawing gesture.
 *
 * Sizes are millimetres. The `parameters` seed the drag defaults (width/height/
 * radius/sides) so a single click drops a sensible starter shape.
 */
import type { ToolDefinition, ToolParam } from "./toolTypes";

/** Shared width/height parameters for box-like shapes. */
const sizeParams: ToolParam[] = [
  { id: "width", label: "Width", type: "number", default: 100, min: 1, max: 5000, step: 1, unit: "mm" },
  { id: "height", label: "Height", type: "number", default: 100, min: 1, max: 5000, step: 1, unit: "mm" },
];

/** Shared radius parameter for round shapes. */
const radiusParams: ToolParam[] = [
  { id: "radius", label: "Radius", type: "number", default: 50, min: 1, max: 2500, step: 1, unit: "mm" },
];

export const geometryTools: ToolDefinition[] = [
  {
    id: "geometry.rect",
    name: "Rectangle",
    category: "geometry",
    icon: "▭",
    description: "Draw a box shape — great for panels, walls and floors.",
    hint: "Click and drag to draw a rectangle. Hold to make it any size you like.",
    shortcut: "R",
    tooltipAnimation: "draw-rect",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "rect",
    parameters: sizeParams,
    keywords: ["box", "panel", "wall", "square", "block", "board"],
    undoable: true,
  },
  {
    id: "geometry.roundedRect",
    name: "Rounded Rectangle",
    category: "geometry",
    icon: "▢",
    description: "A box with soft, rounded corners.",
    hint: "Like a rectangle, but the corners are gently curved.",
    tooltipAnimation: "draw-rounded-rect",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "roundedRect",
    parameters: [
      ...sizeParams,
      { id: "radius", label: "Corner", type: "number", default: 12, min: 0, max: 500, step: 1, unit: "mm" },
    ],
    keywords: ["box", "round", "soft", "corner", "panel"],
    undoable: true,
  },
  {
    id: "geometry.square",
    name: "Square",
    category: "geometry",
    icon: "□",
    description: "A shape with four equal sides.",
    hint: "Drag to draw a perfect square — all sides the same length.",
    tooltipAnimation: "draw-square",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "square",
    parameters: [
      { id: "width", label: "Size", type: "number", default: 100, min: 1, max: 5000, step: 1, unit: "mm" },
    ],
    keywords: ["box", "equal", "tile"],
    undoable: true,
  },
  {
    id: "geometry.circle",
    name: "Circle",
    category: "geometry",
    icon: "○",
    description: "Draw a round circle — perfect for wheels and windows.",
    hint: "Click and drag out from the middle to make a circle.",
    shortcut: "C",
    tooltipAnimation: "draw-circle",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "circle",
    parameters: radiusParams,
    keywords: ["round", "wheel", "dot", "hole", "disc", "window"],
    undoable: true,
  },
  {
    id: "geometry.ellipse",
    name: "Ellipse",
    category: "geometry",
    icon: "⬭",
    description: "A stretched circle — like an egg or an oval.",
    hint: "Drag to draw an oval that can be wide or tall.",
    tooltipAnimation: "draw-ellipse",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "ellipse",
    parameters: sizeParams,
    keywords: ["oval", "egg", "round", "stretched"],
    undoable: true,
  },
  {
    id: "geometry.triangle",
    name: "Triangle",
    category: "geometry",
    icon: "△",
    description: "A pointy three-sided shape — great for roofs.",
    hint: "Drag to draw a triangle with three straight sides.",
    tooltipAnimation: "draw-triangle",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "triangle",
    parameters: sizeParams,
    keywords: ["roof", "pointy", "three", "wedge"],
    undoable: true,
  },
  {
    id: "geometry.polygon",
    name: "Polygon",
    category: "geometry",
    icon: "⬠",
    description: "A many-sided shape — pick how many sides you want.",
    hint: "Drag to draw a shape with lots of equal straight sides.",
    shortcut: "P",
    tooltipAnimation: "draw-polygon",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "polygon",
    parameters: [
      ...radiusParams,
      { id: "sides", label: "Sides", type: "number", default: 5, min: 3, max: 24, step: 1 },
    ],
    keywords: ["pentagon", "many", "sides", "shape"],
    undoable: true,
  },
  {
    id: "geometry.star",
    name: "Star",
    category: "geometry",
    icon: "★",
    description: "A twinkly star with pointy tips.",
    hint: "Drag to draw a star — choose how many points it has.",
    shortcut: "S",
    tooltipAnimation: "draw-star",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "star",
    parameters: [
      ...radiusParams,
      { id: "points", label: "Points", type: "number", default: 5, min: 3, max: 20, step: 1 },
      { id: "innerRadius", label: "Inner", type: "number", default: 20, min: 1, max: 2500, step: 1, unit: "mm" },
    ],
    keywords: ["twinkle", "points", "sky", "sparkle"],
    undoable: true,
  },
  {
    id: "geometry.line",
    name: "Line",
    category: "geometry",
    icon: "╱",
    description: "Draw a straight line from one point to another.",
    hint: "Click where the line starts, drag to where it ends.",
    shortcut: "L",
    tooltipAnimation: "draw-line",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "line",
    parameters: sizeParams,
    keywords: ["straight", "edge", "stroke", "segment"],
    undoable: true,
  },
  {
    id: "geometry.arc",
    name: "Arc",
    category: "geometry",
    icon: "◜",
    description: "A curved line — like a slice of a circle.",
    hint: "Drag to draw a bendy curve.",
    tooltipAnimation: "draw-arc",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "arc",
    parameters: radiusParams,
    keywords: ["curve", "bend", "bow", "rainbow"],
    undoable: true,
  },
  {
    id: "geometry.hexagon",
    name: "Hexagon",
    category: "geometry",
    icon: "⬡",
    description: "A six-sided shape — like a honeycomb.",
    hint: "Drag to draw a shape with six equal sides.",
    tooltipAnimation: "draw-hexagon",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "hexagon",
    parameters: radiusParams,
    keywords: ["six", "honeycomb", "bee", "nut"],
    undoable: true,
  },
  {
    id: "geometry.octagon",
    name: "Octagon",
    category: "geometry",
    icon: "⯃",
    description: "An eight-sided shape — like a stop sign.",
    hint: "Drag to draw a shape with eight equal sides.",
    tooltipAnimation: "draw-octagon",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "octagon",
    parameters: radiusParams,
    keywords: ["eight", "stop", "sign"],
    undoable: true,
  },
  {
    id: "geometry.ring",
    name: "Ring",
    category: "geometry",
    icon: "◎",
    description: "A circle with a hole in the middle — like a donut.",
    hint: "Drag to draw a ring; the middle stays empty.",
    tooltipAnimation: "draw-ring",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "ring",
    parameters: [
      ...radiusParams,
      { id: "innerRadius", label: "Hole", type: "number", default: 25, min: 1, max: 2500, step: 1, unit: "mm" },
    ],
    keywords: ["donut", "washer", "hole", "loop", "round"],
    undoable: true,
  },
  {
    id: "geometry.capsule",
    name: "Capsule",
    category: "geometry",
    icon: "▬",
    description: "A pill shape with two rounded ends.",
    hint: "Drag to draw a stretched shape with smooth round ends.",
    tooltipAnimation: "draw-capsule",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "capsule",
    parameters: sizeParams,
    keywords: ["pill", "stadium", "rounded", "lozenge"],
    undoable: true,
  },
  {
    id: "geometry.slot",
    name: "Slotted Hole",
    category: "geometry",
    icon: "⬓",
    description: "A long thin hole shape — great for fitting tabs.",
    hint: "Drag to draw a slot that a tab can slide into.",
    tooltipAnimation: "draw-slot",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "slot",
    parameters: [
      { id: "width", label: "Length", type: "number", default: 80, min: 1, max: 5000, step: 1, unit: "mm" },
      { id: "height", label: "Width", type: "number", default: 12, min: 1, max: 2000, step: 1, unit: "mm" },
    ],
    keywords: ["groove", "channel", "tab", "cut"],
    undoable: true,
  },
  {
    id: "geometry.trapezoid",
    name: "Trapezoid",
    category: "geometry",
    icon: "⏢",
    description: "A shape with a flat top and a wider bottom.",
    hint: "Drag to draw a trapezoid — one side is wider than the other.",
    tooltipAnimation: "draw-trapezoid",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "trapezoid",
    parameters: sizeParams,
    keywords: ["slope", "ramp", "wedge", "roof"],
    undoable: true,
  },
  {
    id: "geometry.diamond",
    name: "Diamond",
    category: "geometry",
    icon: "◇",
    description: "A tilted square that stands on its point.",
    hint: "Drag to draw a diamond shape.",
    tooltipAnimation: "draw-diamond",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "diamond",
    parameters: sizeParams,
    keywords: ["rhombus", "gem", "kite", "tilt"],
    undoable: true,
  },
  {
    id: "geometry.parallelogram",
    name: "Parallelogram",
    category: "geometry",
    icon: "▰",
    description: "A leaning box shape with slanted sides.",
    hint: "Drag to draw a slanted box that leans to one side.",
    tooltipAnimation: "draw-parallelogram",
    supportedModes: ["2d"],
    kind: "draw",
    createsShape: "parallelogram",
    parameters: sizeParams,
    keywords: ["slant", "lean", "skew", "tilt"],
    undoable: true,
  },
];
