/**
 * 3D Solid Representation Domain Types.
 *
 * CRITICAL DESIGN REQUIREMENT:
 * 3D solid representations generated by this conversion layer exist strictly in
 * piece-local coordinate space (z in [-thickness/2, +thickness/2]).
 * Customer assembly angles and spatial transforms are NOT assigned here.
 */
import type { ID } from "@/core/model/types";
import type { Box3D } from "../geometry/types";

export interface SolidMeshBuffer3D {
  /** Flat array of 3D vertex positions [x0, y0, z0, x1, y1, z1, ...]. */
  positions: Float32Array;
  /** Flat array of 3D vertex normals [nx0, ny0, nz0, ...]. */
  normals: Float32Array;
  /** Flat array of triangle face indices [i0, j0, k0, ...]. */
  indices: Uint32Array;
  /** Optional texture UV coordinates [u0, v0, u1, v1, ...]. */
  uvs?: Float32Array;
  /** Local 3D bounding box spanning [min, max] in piece local space. */
  bounds: Box3D;
}

export interface SolidRepresentation3D {
  pieceId: ID;
  /** Local 3D solid mesh defined strictly in piece local coordinate space. */
  localMesh: SolidMeshBuffer3D;
  /** Total calculated physical volume in mm^3. */
  volumeMm3: number;
  /** Total calculated surface area in mm^2. */
  surfaceAreaMm2: number;
  /** Physical mass in grams (volume * density). */
  massGrams: number;
  /** Extrusion depth / stock cardboard thickness (mm). */
  thickness: number;
  materialId: ID;
}

export interface SolidValidationIssue {
  severity: "ok" | "warning" | "error";
  code: string;
  message: string;
  refIds?: ID[];
}

export interface SolidValidationReport {
  level: "ok" | "warning" | "error";
  issues: SolidValidationIssue[];
}
