/**
 * Connector tools — place physical attachment features (tabs, slots, holes,
 * pegs, pins, dowels, notches, hinges, magnets, snaps, edge/corner joins and
 * glue surfaces) onto the active part. All are kind "connector": selecting one
 * arms the canvas, which drops a connector under the cursor via `addConnector`
 * (see @/core/store/actions) using this tool's `createsConnector` type and the
 * collected `parameters` as overrides.
 */
import type { ToolDefinition, ToolParam } from "./toolTypes";

/** Rectangular footprint params shared by width/height-driven connectors. */
function rectParams(width: number, height: number, depth: number): ToolParam[] {
  return [
    { id: "width", label: "Width", type: "number", default: width, min: 1, max: 500, step: 0.5, unit: "mm" },
    { id: "height", label: "Height", type: "number", default: height, min: 1, max: 500, step: 0.5, unit: "mm" },
    { id: "depth", label: "Depth", type: "number", default: depth, min: 0, max: 200, step: 0.5, unit: "mm" },
  ];
}

/** Round footprint params shared by diameter-driven connectors. */
function roundParams(diameter: number, depth: number): ToolParam[] {
  return [
    { id: "diameter", label: "Diameter", type: "number", default: diameter, min: 1, max: 200, step: 0.5, unit: "mm" },
    { id: "depth", label: "Depth", type: "number", default: depth, min: 0, max: 200, step: 0.5, unit: "mm" },
  ];
}

export const connectorTools: ToolDefinition[] = [
  {
    id: "connector.tab",
    name: "Tab",
    category: "connector",
    icon: "▱",
    description: "A tab pokes out to lock into a slot.",
    hint: "Adds a rectangular tab that sticks out from the edge of the part. Pair it with a slot on the mating part so the two pieces click together.",
    tooltipAnimation: "tab-slot",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "tab",
    parameters: rectParams(12, 4, 4),
    keywords: ["tab", "tongue", "protrusion", "lock", "joint"],
    undoable: true,
  },
  {
    id: "connector.slot",
    name: "Slot",
    category: "connector",
    icon: "▬",
    description: "A slot cuts a gap so a tab can slide in and lock.",
    hint: "Adds a rectangular slot opening that receives a matching tab from another part, holding the two pieces together.",
    tooltipAnimation: "tab-slot",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "slot",
    parameters: rectParams(12, 4, 4),
    keywords: ["slot", "slit", "opening", "receiver", "joint"],
    undoable: true,
  },
  {
    id: "connector.hole",
    name: "Hole",
    category: "connector",
    icon: "◯",
    description: "A round hole for a peg or dowel to plug into.",
    hint: "Cuts a circular hole through the part. Use it with a peg or dowel on the other part to make a snug plug-in joint.",
    tooltipAnimation: "cut-hole",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "hole",
    parameters: roundParams(6, 4),
    keywords: ["hole", "bore", "drill", "socket", "receiver"],
    undoable: true,
  },
  {
    id: "connector.peg",
    name: "Peg",
    category: "connector",
    icon: "●",
    description: "A peg sticks out to plug into a hole.",
    hint: "Adds a round peg that projects from the part's surface and plugs into a hole on the mating part.",
    tooltipAnimation: "peg-hole",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "peg",
    parameters: roundParams(6, 8),
    keywords: ["peg", "plug", "dowel", "stud", "insert"],
    undoable: true,
  },
  {
    id: "connector.dowel",
    name: "Dowel",
    category: "connector",
    icon: "⬤",
    description: "A sturdy round dowel locks two parts together.",
    hint: "Adds a thick round dowel connector that plugs deep into a hole for a strong, hidden joint.",
    tooltipAnimation: "peg-hole",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "dowel",
    parameters: roundParams(8, 10),
    keywords: ["dowel", "peg", "rod", "insert", "joint"],
    undoable: true,
  },
  {
    id: "connector.notch",
    name: "Notch",
    category: "connector",
    icon: "⊔",
    description: "A notch cuts a step so a tab can rest into place.",
    hint: "Cuts a rectangular notch out of the part's edge so a tab (or another part's edge) can seat into it.",
    tooltipAnimation: "cut-hole",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "notch",
    parameters: rectParams(10, 5, 5),
    keywords: ["notch", "step", "cutout", "seat", "joint"],
    undoable: true,
  },
  {
    id: "connector.hinge",
    name: "Hinge",
    category: "connector",
    icon: "⧉",
    description: "A hinge lets two parts swing open and closed.",
    hint: "Adds a hinge connector so two parts can pivot relative to each other, like a lid or a door.",
    tooltipAnimation: "hinge-swing",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "hinge",
    parameters: rectParams(20, 6, 4),
    keywords: ["hinge", "pivot", "swing", "lid", "door"],
    undoable: true,
  },
  {
    id: "connector.magnet",
    name: "Magnet",
    category: "connector",
    icon: "🧲",
    description: "A magnet snaps two parts together without glue.",
    hint: "Adds a round magnet pocket. Two facing magnets pull the parts together for a quick, removable join.",
    tooltipAnimation: "magnet-snap",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "magnet",
    parameters: roundParams(8, 3),
    keywords: ["magnet", "snap", "removable", "attach"],
    undoable: true,
  },
  {
    id: "connector.snap",
    name: "Snap Fit",
    category: "connector",
    icon: "⌁",
    description: "A springy snap fit clicks two parts together.",
    hint: "Adds a flexible snap-fit connector that clicks into a slot-like receiver, holding parts together without hardware.",
    tooltipAnimation: "snap-fit",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "snap",
    parameters: rectParams(10, 6, 5),
    keywords: ["snap", "click", "fastener", "clip"],
    undoable: true,
  },
  {
    id: "connector.edge",
    name: "Edge Join",
    category: "connector",
    icon: "▬",
    description: "An edge join glues one part's edge flush to another.",
    hint: "Marks a straight edge as a connector so it can be matched flush against another part's edge or a tab.",
    tooltipAnimation: "edge-join",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "edge",
    parameters: rectParams(20, 4, 4),
    keywords: ["edge", "flush", "butt joint", "seam"],
    undoable: true,
  },
  {
    id: "connector.corner",
    name: "Corner Join",
    category: "connector",
    icon: "⌐",
    description: "A corner join meets two parts at a right angle.",
    hint: "Marks a corner connector for parts that meet at 90 degrees, like the sides of a box.",
    tooltipAnimation: "corner-join",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "corner",
    parameters: rectParams(12, 12, 4),
    keywords: ["corner", "right angle", "box joint", "meet"],
    undoable: true,
  },
  {
    id: "connector.surface",
    name: "Surface Bond",
    category: "connector",
    icon: "▦",
    description: "A surface bond glues a flat area to another part.",
    hint: "Marks a flat glue or contact area used to bond one part's face to another, for lamination or flat panel joins.",
    tooltipAnimation: "surface-glue",
    supportedModes: ["2d"],
    kind: "connector",
    createsConnector: "surface",
    parameters: rectParams(16, 16, 2),
    keywords: ["surface", "glue", "bond", "face", "laminate"],
    undoable: true,
  },
];
